// src/screens/payment/PaymentScreen.tsx
// Mock PayHere checkout. A real PayHere flow redirects to their hosted
// checkout page/SDK using a hash generated by a real backend — see the note
// in payment.types.ts for why that can't happen client-only. This screen
// models the same states (pending -> processing -> paid) so the rest of the
// app (gating property creation on a paid order) is wired correctly.

import React, { useEffect, useState } from 'react';
import { View, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Text, Icon, ActivityIndicator } from 'react-native-paper';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { PropertyStackParamList } from '@/navigation/PropertyNavigator';
import { useAppDispatch, useAppSelector } from '@/hooks/redux';
import { startCheckout, confirmPayment, resetPayment } from '@/redux/payment/paymentSlice';
import { createProperty } from '@/redux/property/propertySlice';
import Button from '@/components/Button/Button';
import { colors } from '@/theme/colors';
import { fonts, type } from '@/theme/typography';
import { moderateScale } from '@/utils/responsive';
import { formatCurrency } from '@/utils/currency';
import { LISTING_FEE_LKR } from '@/types/payment.types';

type Props = NativeStackScreenProps<PropertyStackParamList, 'Payment'>;

type Stage = 'summary' | 'processing' | 'success' | 'error';

export default function PaymentScreen({ route, navigation }: Props) {
  const { formInput } = route.params;
  const dispatch = useAppDispatch();
  const { currentOrder, error } = useAppSelector((state) => state.payment);
  const { isSubmitting } = useAppSelector((state) => state.property);
  const [stage, setStage] = useState<Stage>('summary');

  useEffect(() => {
    dispatch(startCheckout());
    return () => {
      dispatch(resetPayment());
    };
  }, [dispatch]);

  const handlePay = async () => {
    if (!currentOrder) return;
    setStage('processing');

    const confirmResult = await dispatch(confirmPayment(currentOrder.orderId));
    if (!confirmPayment.fulfilled.match(confirmResult)) {
      setStage('error');
      return;
    }

    const createResult = await dispatch(
      createProperty({ input: formInput, paymentOrderId: confirmResult.payload.orderId })
    );
    if (createProperty.fulfilled.match(createResult)) {
      setStage('success');
    } else {
      setStage('error');
    }
  };

  const handleDone = () => {
    navigation.popToTop();
  };

  return (
    <SafeAreaView edges={['top']} style={styles.screen}>
      <View style={styles.header}>
        <View style={styles.brandRow}>
          <View style={styles.brandIconCircle}>
            <Icon source="credit-card-outline" size={18} color={colors.textInverse} />
          </View>
          <Text style={styles.brandText}>PayHere Checkout</Text>
        </View>
      </View>

      <View style={styles.content}>
        {stage === 'summary' && (
          <>
            <Text style={styles.title}>Listing Fee</Text>
            <Text style={styles.subtitle}>
              A one-time fee is required to publish your property so it's visible to everyone.
            </Text>

            <View style={styles.summaryCard}>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Item</Text>
                <Text style={styles.summaryValue}>Property Listing</Text>
              </View>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Property</Text>
                <Text style={styles.summaryValue} numberOfLines={1}>
                  {formInput.title || 'Untitled listing'}
                </Text>
              </View>
              <View style={styles.divider} />
              <View style={styles.summaryRow}>
                <Text style={styles.summaryTotalLabel}>Total</Text>
                <Text style={styles.summaryTotalValue}>{formatCurrency(LISTING_FEE_LKR)}</Text>
              </View>
            </View>

            <Button
              label={`Pay ${formatCurrency(LISTING_FEE_LKR)} with PayHere`}
              onPress={handlePay}
              disabled={!currentOrder}
              style={styles.payButton}
            />
            <Text style={styles.disclaimer}>
              Sandbox checkout — no real payment is processed in this build.
            </Text>
          </>
        )}

        {stage === 'processing' && (
          <View style={styles.centerState}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.processingText}>Processing your payment...</Text>
            <Text style={styles.disclaimer}>Please don't close this screen.</Text>
          </View>
        )}

        {stage === 'success' && (
          <View style={styles.centerState}>
            <View style={styles.successIconCircle}>
              <Icon source="check" size={32} color={colors.textInverse} />
            </View>
            <Text style={styles.title}>Payment Successful</Text>
            <Text style={styles.subtitle}>
              Your listing has been published and is now visible to everyone.
            </Text>
            <Button label="Done" onPress={handleDone} style={styles.payButton} />
          </View>
        )}

        {stage === 'error' && (
          <View style={styles.centerState}>
            <View style={styles.errorIconCircle}>
              <Icon source="close" size={32} color={colors.textInverse} />
            </View>
            <Text style={styles.title}>Payment Failed</Text>
            <Text style={styles.subtitle}>{error ?? 'Something went wrong. Please try again.'}</Text>
            <Button label="Try Again" onPress={() => setStage('summary')} style={styles.payButton} />
            <Button label="Cancel" mode="text" onPress={() => navigation.goBack()} />
          </View>
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingVertical: moderateScale(16),
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  brandIconCircle: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandText: {
    fontFamily: fonts.displaySemiBold,
    fontSize: moderateScale(type.h3),
    color: colors.text,
  },
  content: {
    flex: 1,
    padding: moderateScale(20),
  },
  title: {
    fontFamily: fonts.displayBold,
    fontSize: moderateScale(type.h1),
    color: colors.text,
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: fonts.body,
    fontSize: moderateScale(type.caption),
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 24,
    lineHeight: moderateScale(19),
  },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: moderateScale(16),
    marginBottom: 24,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  summaryLabel: {
    fontFamily: fonts.body,
    fontSize: moderateScale(type.caption),
    color: colors.textMuted,
  },
  summaryValue: {
    fontFamily: fonts.bodyMedium,
    fontSize: moderateScale(type.caption),
    color: colors.text,
    maxWidth: '60%',
    textAlign: 'right',
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 8,
  },
  summaryTotalLabel: {
    fontFamily: fonts.displaySemiBold,
    fontSize: moderateScale(type.h3),
    color: colors.text,
  },
  summaryTotalValue: {
    fontFamily: fonts.displayBold,
    fontSize: moderateScale(type.h3),
    color: colors.primary,
  },
  payButton: {
    marginTop: 4,
  },
  disclaimer: {
    fontFamily: fonts.body,
    fontSize: moderateScale(type.micro),
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 12,
  },
  centerState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingText: {
    fontFamily: fonts.bodyMedium,
    fontSize: moderateScale(type.body),
    color: colors.text,
    marginTop: 16,
    marginBottom: 4,
  },
  successIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.success,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  errorIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
});
